"""Local-only audio library registry.

This module is intentionally separate from the cloud music/SFX architecture.
It treats the machine's local audio folders as the complete development library:

    campaign_data/web_audio/  -> music
    campaign_data/web_sfx/    -> SFX

No audio bytes are embedded in GitHub source. At runtime the registry scans the
local folders and also exposes the procedural SFX catalog so every generated
SFX remains discoverable by the local web player.

The local registry is a development/offline mode. Production/shared hosting can
use the cloud library service instead, without downloading the shared library.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from .config import DATA_DIR
from .music_service import AUDIO_EXTENSIONS, make_track
from .sfx_engine import _STARTER, SFX_LIBRARY_DIR

LOCAL_MUSIC_DIR = Path(DATA_DIR) / "web_audio"
LOCAL_SFX_DIR = Path(DATA_DIR) / "web_sfx"


def _tags_from_name(name: str) -> list[str]:
    raw = name.casefold().replace("-", "_")
    parts = [part for part in raw.replace(".", "_").split("_") if part]
    return list(dict.fromkeys(parts))


def list_local_music() -> list[dict[str, Any]]:
    """Index every supported music file currently present on this machine."""
    if not LOCAL_MUSIC_DIR.exists():
        return []
    tracks: list[dict[str, Any]] = []
    for path in sorted(LOCAL_MUSIC_DIR.rglob("*")):
        if not path.is_file() or path.suffix.casefold() not in AUDIO_EXTENSIONS:
            continue
        relative = path.relative_to(LOCAL_MUSIC_DIR).as_posix()
        tracks.append(make_track(relative, tags=_tags_from_name(path.stem), source="local-library"))
    return tracks


def list_local_sfx() -> list[dict[str, Any]]:
    """Index every local SFX WAV plus every procedural starter SFX definition."""
    LOCAL_SFX_DIR.mkdir(parents=True, exist_ok=True)
    sounds: dict[str, dict[str, Any]] = {}

    # Generated starter SFX catalog: all definitions are available even before
    # their WAV has been generated by ensure_starter_library().
    for sound_id, item in _STARTER.items():
        sounds[sound_id] = {
            "id": sound_id,
            "name": sound_id.replace("_", " ").title(),
            "filename": f"{sound_id}.wav",
            "url": f"/media/sfx/{sound_id}.wav",
            "tags": list(item.get("tags") or []),
            "source": "generated-starter",
        }

    # Include any additional local SFX files, including expanded/custom assets.
    if LOCAL_SFX_DIR.exists():
        for path in sorted(LOCAL_SFX_DIR.rglob("*.wav")):
            relative = path.relative_to(LOCAL_SFX_DIR).as_posix()
            sound_id = path.stem
            sounds[sound_id] = {
                "id": sound_id,
                "name": sound_id.replace("_", " ").title(),
                "filename": relative,
                "url": "/media/sfx/" + relative,
                "tags": _tags_from_name(path.stem),
                "source": "local-library",
            }

    return list(sounds.values())


def build_local_library() -> dict[str, Any]:
    """Return the complete local development music + SFX catalog."""
    music = list_local_music()
    sfx = list_local_sfx()
    return {
        "version": 1,
        "mode": "local",
        "music_root": str(LOCAL_MUSIC_DIR),
        "sfx_root": str(LOCAL_SFX_DIR),
        "music": music,
        "sfx": sfx,
        "counts": {"music": len(music), "sfx": len(sfx)},
    }


__all__ = [
    "LOCAL_MUSIC_DIR",
    "LOCAL_SFX_DIR",
    "build_local_library",
    "list_local_music",
    "list_local_sfx",
]
